"""Report generation — assemble lens results into formatted output."""

import json

from pramana.config import Settings
from pramana.pipeline.hypothesis import HypothesisQuery
from pramana.pipeline.orchestrator import AnalysisResults


def generate_report(
    results: AnalysisResults,
    query: HypothesisQuery,
    output_format: str,
    settings: Settings,
) -> str:
    """Generate a report from analysis results."""
    if output_format == "json":
        return _generate_json(results, query)
    else:
        return _generate_markdown(results, query)


def _generate_json(results: AnalysisResults, query: HypothesisQuery) -> str:
    """Generate JSON report."""
    report = {
        "hypothesis": {
            "domains": query.domains,
            "topics": query.topics,
            "methods": query.methods,
            "evaluation_focus": query.evaluation_focus,
            "initiation_context": query.initiation_context,
        },
        "active_lenses": results.active_lenses,
        "lens_results": [
            {
                "lens": r.lens_name,
                "title": r.title,
                "summary": r.summary,
                "content": r.content,
            }
            for r in results.lens_results
        ],
    }
    return json.dumps(report, indent=2)


def _generate_markdown(results: AnalysisResults, query: HypothesisQuery) -> str:
    """Generate Markdown report."""
    lines: list[str] = []

    # Header
    lines.append("# Pramana Research Analysis Report")
    lines.append("")

    # Hypothesis summary
    lines.append("## Hypothesis")
    lines.append(f"**Domains:** {', '.join(query.domains)}")
    lines.append(f"**Topics:** {', '.join(query.topics)}")
    if query.methods:
        lines.append(f"**Methods:** {', '.join(query.methods)}")
    if query.evaluation_focus:
        lines.append(f"**Evaluation Focus:** {', '.join(query.evaluation_focus)}")
    lines.append(f"**Context:** {query.initiation_context}")
    lines.append("")

    # Active lenses
    lines.append(f"**Active Lenses:** {', '.join(results.active_lenses)}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Each lens result
    for result in results.lens_results:
        lines.append(f"## {result.title}")
        lines.append("")
        lines.append(f"*{result.summary}*")
        lines.append("")

        if result.lens_name == "evidence_table":
            lines.extend(_format_evidence_table(result.content))
        elif result.lens_name == "gap_discovery":
            lines.extend(_format_gaps(result.content))
        elif result.lens_name == "meta_analysis":
            lines.extend(_format_meta_analysis(result.content))
        elif result.lens_name == "venue_mapping":
            lines.extend(_format_venue_mapping(result.content))
        elif result.lens_name == "research_planning":
            lines.extend(_format_research_planning(result.content))
        else:
            lines.append(f"```json\n{json.dumps(result.content, indent=2)}\n```")

        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("*Generated by Pramana — hypothesis-driven research assistant*")
    return "\n".join(lines)


def _format_evidence_table(content: dict) -> list[str]:
    """Format evidence table content as Markdown."""
    lines: list[str] = []

    lines.append(f"**Total facts:** {content.get('total_facts', 0)} | "
                 f"**Papers with evidence:** {content.get('papers_with_evidence', 0)}")
    lines.append("")

    tables = content.get("tables", {})
    for fact_type, facts in tables.items():
        lines.append(f"### {fact_type.title()} ({len(facts)})")
        lines.append("")
        lines.append("| Content | Quote | Location | Paper |")
        lines.append("|---------|-------|----------|-------|")
        for f in facts[:20]:  # Limit to 20 per type
            content_text = f.get("content", "").replace("|", "\\|")
            quote = f.get("direct_quote", "")[:80].replace("|", "\\|")
            location = f.get("location", "").replace("|", "\\|")
            paper = f.get("paper_title", "").replace("|", "\\|")
            lines.append(f"| {content_text} | {quote} | {location} | {paper} |")
        lines.append("")

    return lines


def _format_gaps(content: dict) -> list[str]:
    """Format gap discovery content."""
    lines: list[str] = []
    gaps = content.get("gaps", [])

    if not gaps:
        lines.append("No significant gaps identified.")
        return lines

    for i, gap in enumerate(gaps, 1):
        desc = gap.get("description", "")
        evidence = gap.get("evidence", "")
        severity = gap.get("severity", "")
        lines.append(f"### Gap {i}: {desc}")
        lines.append(f"**Severity:** {severity}")
        lines.append(f"**Evidence:** {evidence}")
        papers = gap.get("supporting_papers", [])
        if papers:
            lines.append(f"**Supporting papers:** {', '.join(str(p) for p in papers)}")
        lines.append("")

    return lines


def _format_meta_analysis(content: dict) -> list[str]:
    """Format meta-analysis content."""
    lines: list[str] = []

    top_terms = content.get("top_terms", {})
    if top_terms:
        lines.append("### Top Terms")
        lines.append("| Term | Count |")
        lines.append("|------|-------|")
        for term, count in list(top_terms.items())[:15]:
            lines.append(f"| {term} | {count} |")
        lines.append("")

    year_dist = content.get("year_distribution", {})
    if year_dist:
        lines.append("### Year Distribution")
        lines.append("| Year | Papers |")
        lines.append("|------|--------|")
        for year, count in sorted(year_dist.items()):
            lines.append(f"| {year} | {count} |")
        lines.append("")

    return lines


def _format_venue_mapping(content: dict) -> list[str]:
    """Format venue mapping content."""
    lines: list[str] = []
    summary = content.get("venue_evidence_summary", {})

    if summary:
        lines.append("### Venue Overview")
        lines.append("| Venue | Tier | Papers | Facts |")
        lines.append("|-------|------|--------|-------|")
        for venue, data in summary.items():
            tier = data.get("tier", "?")
            papers = data.get("paper_count", 0)
            facts = data.get("fact_count", 0)
            lines.append(f"| {venue} | {tier} | {papers} | {facts} |")
        lines.append("")

    analysis = content.get("venue_analysis", [])
    for item in analysis:
        venue = item.get("venue", "")
        lines.append(f"### {venue}")
        for pattern in item.get("patterns", []):
            lines.append(f"- {pattern}")
        lines.append("")

    return lines


def _format_research_planning(content: dict) -> list[str]:
    """Format research planning content."""
    lines: list[str] = []

    directions = content.get("directions", [])
    if directions:
        lines.append("### Suggested Research Directions")
        for d in directions:
            if isinstance(d, dict):
                lines.append(f"- **{d.get('area', '')}**: {d.get('rationale', d.get('description', ''))}")
            else:
                lines.append(f"- {d}")
        lines.append("")

    recommendations = content.get("recommendations", [])
    if recommendations:
        lines.append("### Recommendations")
        for r in recommendations:
            if isinstance(r, dict):
                lines.append(f"- {r.get('text', r.get('description', ''))}")
            else:
                lines.append(f"- {r}")
        lines.append("")

    return lines
